name: release-chart

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  release-chart:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure Git User
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name  "${{ github.actor }}"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.1.0

      - name: Publish Helm Chart
        run: |
          make publish-helm-chart
          cd third-party/troubleshoot-live && git add . && git commit -m "Release Helm Chart" && git push
